### ISSUE TITLE
the newest mod of 1.18.2 crashes the game

### ISSUE THREAD

**Issue by shownfish** [joshuaepstein/advancementtrophies#6]
I have tried ,even only load this mod will crash the game.the forge version is 40.1.68

**Comment by joshuaepstein** [comment]
Can you send me a crash report

**Comment by shownfish** [comment]
[crash-2022-08-03_21.56.53-fml.txt](https://github.com/joshuaepstein/advancementtrophies/files/9252450/crash-2022-08-03_21.56.53-fml.txt)

**Comment by joshuaepstein** [comment]
I can see when reading the error log that a mod is the incorrect version. Here is the bit that explains this ![image](https://user-images.githubusercontent.com/55663195/182659159-9073158c-9376-44f3-945e-c32a2ff8ff07.jpeg)

**Comment by shownfish** [comment]
Sorry I gave you the wrong file，this one is the correct report
[crash-2022-08-04_9.33.45-fml.txt](https://github.com/joshuaepstein/advancementtrophies/files/9256012/crash-2022-08-04_9.33.45-fml.txt)

**Comment by shownfish** [comment]
Sorry I gave you the wrong file，this one is the correct report
[crash-2022-08-04_09.33.45-fml.txt](https://github.com/joshuaepstein/advancementtrophies/files/9256069/crash-2022-08-04_09.33.45-fml.txt)

**Comment by DeleteMetaInf** [comment]
My game also crashes trying to run it with Advancement Trophies. It crashes very quickly after booting the game. I got the same crash report as @shownfish.

I assume that it’s caused by some simple syntax error based on the crash message:
`java.lang.IllegalArgumentException: p1.3-forge-1.18.2: Version string does not start with a number`

**Crash report:** https://pastebin.com/raw/vpNKtVvh
**latest.log:** https://pastebin.com/raw/pcp404FH

### Versions
* **Minecraft:** 1.18.2
* **Forge:** 40.1.69 (latest for 1.18.2)
* **Advancement Trophies:** 1.3 (latest for 1.18.2)

**Comment by joshuaepstein** [comment]
I am aware with this issue, in a day or two there will be a new update for this version which will be the 1.4 version. Sorry for any troubles

**Comment by DeleteMetaInf** [comment]
Great to hear. Thank you and no worries!

**Comment by joshuaepstein** [comment]
1.18.2 version was accepted on curseforge. Should be all working now. Let me know if it works

**Comment by shownfish** [comment]
It works now.thank you

**Comment by DeleteMetaInf** [comment]
Thanks for the update!
